apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-anime-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ml-anime-app
  template:
    metadata:
      labels:
        app: ml-anime-app
    spec:
      containers:
      - name: ml-anime-cluster
        image: gcr.io/mlops-project-2-459316/ml-anime-project:latest
        ports:
        - containerPort: 5000  # Replace with the port your app listens on
---
apiVersion: v1
kind: Service
metadata:
  name: ml-anime-app-service
spec:
  type: LoadBalancer
  selector:
    app: ml-anime-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000

